version: '3.8'

services:
  web:
    build: code
    depends_on:
      - db
    ports:
      - '8000:8000'
    env_file:
      - .env
    command: runserver 0.0.0.0:8000

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
