# [START django_app]
runtime: python38

entrypoint: gunicorn -b :$PORT -w 1 fotojenicoServer.wsgi
env_variables:
  # Config
  DEBUG: "False"
  REST_PAGE_SIZE: "10"

vpc_access_connector:
  name: projects/fotojenico/locations/europe-west6/connectors/connector2

handlers:
- url: /static
  static_dir: static/
  secure: always

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
# [END django_app]
