# Generated by Django 3.1.3 on 2020-11-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.BigIntegerField(default=0),
        ),
    ]
