# Generated by Django 3.1.3 on 2020-11-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='point_multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
    ]
