# Generated by Django 3.1.3 on 2020-11-08 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201107_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='multiplier_end_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='suspicion_level',
            field=models.IntegerField(default=0),
        ),
    ]
