# Generated by Django 3.1.3 on 2020-11-18 21:37

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20201108_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shown_username',
            field=models.TextField(default='', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ImageField(blank=True, default='', upload_to=app.models.photo_path),
        ),
        migrations.CreateModel(
            name='Multiplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('multiply_times', models.IntegerField(default=1)),
                ('bought_at', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('stackable', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
