# Generated by Django 3.1.3 on 2020-11-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201119_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shown_username',
            field=models.TextField(default='', max_length=25),
        ),
    ]
