# Generated by Django 3.1.3 on 2020-11-24 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20201119_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='watch_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Sent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.post')),
            ],
        ),
    ]
