# Generated by Django 3.1.3 on 2020-11-28 16:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20201126_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='owner',
        ),
        migrations.AddField(
            model_name='achievementprogress',
            name='progress_steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievements',
            name='step_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='achievementprogress',
            name='progress_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
