# Generated by Django 3.1.3 on 2020-11-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201128_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='description',
        ),
    ]
