# Generated by Django 3.1.3 on 2020-11-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_achievements_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievementprogress',
            old_name='progress_steps',
            new_name='progress_step',
        ),
    ]
