# Generated by Django 3.1.3 on 2020-11-29 18:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201128_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementprogress',
            name='progress_percent',
        ),
        migrations.AddField(
            model_name='achievementprogress',
            name='progress_reset_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='achievementprogress',
            name='progress_step',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PostPriority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.post')),
            ],
        ),
    ]
