# Generated by Django 3.1.3 on 2020-12-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201129_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementprogress',
            name='progress_step',
            field=models.IntegerField(default=0),
        ),
    ]
