# Generated by Django 3.1.4 on 2020-12-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201218_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementprogress',
            name='step_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='achievementprogress',
            name='achievement',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Achievements',
        ),
    ]
